package expr

const (
	ChannelLayoutMono          = ChannelLayout("mono")
	ChannelLayoutStereo        = ChannelLayout("stereo")
	ChannelLayout_2_1          = ChannelLayout("2.1")
	ChannelLayout_3_0          = ChannelLayout("3.0")
	ChannelLayout_3_0_Back     = ChannelLayout("3.0(back)")
	ChannelLayout_4_0          = ChannelLayout("4.0")
	ChannelLayoutQuad          = ChannelLayout("quad")
	ChannelLayoutQuadSide      = ChannelLayout("quad(side)")
	ChannelLayout_3_1          = ChannelLayout("3.1")
	ChannelLayout_5_0          = ChannelLayout("5.0")
	ChannelLayout_5_0_Side     = ChannelLayout("5.0(side)")
	ChannelLayout_4_1          = ChannelLayout("4.1")
	ChannelLayout_5_1          = ChannelLayout("5.1")
	ChannelLayout_5_1_Side     = ChannelLayout("5.1(side)")
	ChannelLayout_6_0          = ChannelLayout("6.0")
	ChannelLayout_6_0_Front    = ChannelLayout("6.0(front)")
	ChannelLayoutHexagonal     = ChannelLayout("hexagonal")
	ChannelLayout_6_1          = ChannelLayout("6.1")
	ChannelLayout_6_1_Back     = ChannelLayout("6.1(back)")
	ChannelLayout_6_1_Front    = ChannelLayout("6.1(front)")
	ChannelLayout_7_0          = ChannelLayout("7.0")
	ChannelLayout_7_0_Front    = ChannelLayout("7.0(front)")
	ChannelLayout_7_1          = ChannelLayout("7.1")
	ChannelLayout_7_1_Wide     = ChannelLayout("7.1(wide)")
	ChannelLayout_7_1_WideSide = ChannelLayout("7.1(wide-side)")
	ChannelLayout_7_1_Top      = ChannelLayout("7.1(top)")
	ChannelLayoutOctagonal     = ChannelLayout("octagonal")
	ChannelLayoutCube          = ChannelLayout("cube")
	ChannelLayoutHexadecagonal = ChannelLayout("hexadecagonal")
	ChannelLayoutDownmix       = ChannelLayout("downmix")
	ChannelLayout_22_2         = ChannelLayout("22.2")
)
