// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// AllRGBBuilder corresponds to the "allrgb" FFmpeg filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#allrgb
type AllRGBBuilder interface {
	filter.Filter
	// Size sets the "s" option on the filter.
	Size(width, height int) AllRGBBuilder
	// FrameRate sets the "r" option on the filter.
	FrameRate(frameRate expr.Expr) AllRGBBuilder
	// Duration sets the "d" option on the filter.
	Duration(duration string) AllRGBBuilder
}

// AllRGB creates a new AllRGBBuilder to configure the "allrgb" filter.
func AllRGB(opts ...filter.Option) AllRGBBuilder {
	return &implAllRGBBuilder{
		f: filter.New("allrgb", 1, opts...),
	}
}

type implAllRGBBuilder struct {
	f filter.Filter
}

func (b *implAllRGBBuilder) String() string {
	return b.f.String()
}

func (b *implAllRGBBuilder) Outputs() int {
	return b.f.Outputs()
}

func (b *implAllRGBBuilder) With(key string, value expr.Expr) filter.Filter {
	return b.withOption(key, value)
}

func (b *implAllRGBBuilder) withOption(key string, value expr.Expr) AllRGBBuilder {
	bCopy := *b
	bCopy.f = b.f.With(key, value)
	return &bCopy
}

func (b *implAllRGBBuilder) Size(width, height int) AllRGBBuilder {
	return b.withOption("s", expr.Size(width, height))
}

func (b *implAllRGBBuilder) FrameRate(frameRate expr.Expr) AllRGBBuilder {
	return b.withOption("r", frameRate)
}

func (b *implAllRGBBuilder) Duration(duration string) AllRGBBuilder {
	return b.withOption("d", expr.String(duration))
}
