// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// AlphaextractBuilder Extract an alpha channel as a grayscale image component.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#alphaextract
type AlphaextractBuilder interface {
	filter.Filter
}

// Alphaextract creates a new AlphaextractBuilder to configure the "alphaextract" filter.
func Alphaextract(opts ...filter.Option) AlphaextractBuilder {
	return &implAlphaextractBuilder{
		f: filter.New("alphaextract", 1, opts...),
	}
}

type implAlphaextractBuilder struct {
	f filter.Filter
}

func (alphaextractBuilder *implAlphaextractBuilder) String() string {
	return alphaextractBuilder.f.String()
}

func (alphaextractBuilder *implAlphaextractBuilder) Outputs() int {
	return alphaextractBuilder.f.Outputs()
}

func (alphaextractBuilder *implAlphaextractBuilder) With(key string, value expr.Expr) filter.Filter {
	return alphaextractBuilder.withOption(key, value)
}

func (alphaextractBuilder *implAlphaextractBuilder) withOption(key string, value expr.Expr) AlphaextractBuilder {
	bCopy := *alphaextractBuilder
	bCopy.f = alphaextractBuilder.f.With(key, value)
	return &bCopy
}
