// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// ApsnrBuilder Measure Audio Peak Signal-to-Noise Ratio.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#apsnr
type ApsnrBuilder interface {
	filter.Filter
}

// Apsnr creates a new ApsnrBuilder to configure the "apsnr" filter.
func Apsnr(opts ...filter.Option) ApsnrBuilder {
	return &implApsnrBuilder{
		f: filter.New("apsnr", 1, opts...),
	}
}

type implApsnrBuilder struct {
	f filter.Filter
}

func (apsnrBuilder *implApsnrBuilder) String() string {
	return apsnrBuilder.f.String()
}

func (apsnrBuilder *implApsnrBuilder) Outputs() int {
	return apsnrBuilder.f.Outputs()
}

func (apsnrBuilder *implApsnrBuilder) With(key string, value expr.Expr) filter.Filter {
	return apsnrBuilder.withOption(key, value)
}

func (apsnrBuilder *implApsnrBuilder) withOption(key string, value expr.Expr) ApsnrBuilder {
	bCopy := *apsnrBuilder
	bCopy.f = apsnrBuilder.f.With(key, value)
	return &bCopy
}
