// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// AreverseBuilder Reverse an audio clip.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#areverse
type AreverseBuilder interface {
	filter.Filter
}

// Areverse creates a new AreverseBuilder to configure the "areverse" filter.
func Areverse(opts ...filter.Option) AreverseBuilder {
	return &implAreverseBuilder{
		f: filter.New("areverse", 1, opts...),
	}
}

type implAreverseBuilder struct {
	f filter.Filter
}

func (areverseBuilder *implAreverseBuilder) String() string {
	return areverseBuilder.f.String()
}

func (areverseBuilder *implAreverseBuilder) Outputs() int {
	return areverseBuilder.f.Outputs()
}

func (areverseBuilder *implAreverseBuilder) With(key string, value expr.Expr) filter.Filter {
	return areverseBuilder.withOption(key, value)
}

func (areverseBuilder *implAreverseBuilder) withOption(key string, value expr.Expr) AreverseBuilder {
	bCopy := *areverseBuilder
	bCopy.f = areverseBuilder.f.With(key, value)
	return &bCopy
}
