// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// AsdrBuilder Measure Audio Signal-to-Distortion Ratio.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#asdr
type AsdrBuilder interface {
	filter.Filter
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) AsdrBuilder
}

// Asdr creates a new AsdrBuilder to configure the "asdr" filter.
func Asdr(opts ...filter.Option) AsdrBuilder {
	return &implAsdrBuilder{
		f: filter.New("asdr", 1, opts...),
	}
}

type implAsdrBuilder struct {
	f filter.Filter
}

func (asdrBuilder *implAsdrBuilder) String() string {
	return asdrBuilder.f.String()
}

func (asdrBuilder *implAsdrBuilder) Outputs() int {
	return asdrBuilder.f.Outputs()
}

func (asdrBuilder *implAsdrBuilder) With(key string, value expr.Expr) filter.Filter {
	return asdrBuilder.withOption(key, value)
}

func (asdrBuilder *implAsdrBuilder) withOption(key string, value expr.Expr) AsdrBuilder {
	bCopy := *asdrBuilder
	bCopy.f = asdrBuilder.f.With(key, value)
	return &bCopy
}

func (asdrBuilder *implAsdrBuilder) Enable(enable expr.Expr) AsdrBuilder {
	return asdrBuilder.withOption("enable", enable)
}
