// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// AsettbBuilder Set timebase for the audio output link.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#asettb
type AsettbBuilder interface {
	filter.Filter
	// Expr set expression determining the output timebase (default "intb").
	Expr(expression expr.Expr) AsettbBuilder
	// Tb set expression determining the output timebase (default "intb").
	Tb(tb expr.Expr) AsettbBuilder
}

// Asettb creates a new AsettbBuilder to configure the "asettb" filter.
func Asettb(opts ...filter.Option) AsettbBuilder {
	return &implAsettbBuilder{
		f: filter.New("asettb", 1, opts...),
	}
}

type implAsettbBuilder struct {
	f filter.Filter
}

func (asettbBuilder *implAsettbBuilder) String() string {
	return asettbBuilder.f.String()
}

func (asettbBuilder *implAsettbBuilder) Outputs() int {
	return asettbBuilder.f.Outputs()
}

func (asettbBuilder *implAsettbBuilder) With(key string, value expr.Expr) filter.Filter {
	return asettbBuilder.withOption(key, value)
}

func (asettbBuilder *implAsettbBuilder) withOption(key string, value expr.Expr) AsettbBuilder {
	bCopy := *asettbBuilder
	bCopy.f = asettbBuilder.f.With(key, value)
	return &bCopy
}

func (asettbBuilder *implAsettbBuilder) Expr(expression expr.Expr) AsettbBuilder {
	return asettbBuilder.withOption("expr", expression)
}

func (asettbBuilder *implAsettbBuilder) Tb(tb expr.Expr) AsettbBuilder {
	return asettbBuilder.withOption("tb", tb)
}
