// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// BandrejectBuilder Apply a two-pole Butterworth band-reject filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#bandreject
type BandrejectBuilder interface {
	filter.Filter
	// Frequency set central frequency (from 0 to 999999) (default 3000).
	Frequency(frequency float64) BandrejectBuilder
	// FrequencyExpr set central frequency (from 0 to 999999) (default 3000).
	FrequencyExpr(frequency expr.Expr) BandrejectBuilder
	// F set central frequency (from 0 to 999999) (default 3000).
	F(f float64) BandrejectBuilder
	// FExpr set central frequency (from 0 to 999999) (default 3000).
	FExpr(f expr.Expr) BandrejectBuilder
	// WidthType set filter-width type (from 1 to 5) (default q).
	WidthType(widthType int) BandrejectBuilder
	// WidthTypeExpr set filter-width type (from 1 to 5) (default q).
	WidthTypeExpr(widthType expr.Expr) BandrejectBuilder
	// T set filter-width type (from 1 to 5) (default q).
	T(t int) BandrejectBuilder
	// TExpr set filter-width type (from 1 to 5) (default q).
	TExpr(t expr.Expr) BandrejectBuilder
	// Width set width (from 0 to 99999) (default 0.5).
	Width(width float64) BandrejectBuilder
	// WidthExpr set width (from 0 to 99999) (default 0.5).
	WidthExpr(width expr.Expr) BandrejectBuilder
	// W set width (from 0 to 99999) (default 0.5).
	W(w float64) BandrejectBuilder
	// WExpr set width (from 0 to 99999) (default 0.5).
	WExpr(w expr.Expr) BandrejectBuilder
	// Mix set mix (from 0 to 1) (default 1).
	Mix(mix float64) BandrejectBuilder
	// MixExpr set mix (from 0 to 1) (default 1).
	MixExpr(mix expr.Expr) BandrejectBuilder
	// M set mix (from 0 to 1) (default 1).
	M(m float64) BandrejectBuilder
	// MExpr set mix (from 0 to 1) (default 1).
	MExpr(m expr.Expr) BandrejectBuilder
	// Channels set channels to filter (default "all").
	Channels(channels string) BandrejectBuilder
	// ChannelsExpr set channels to filter (default "all").
	ChannelsExpr(channels expr.Expr) BandrejectBuilder
	// C set channels to filter (default "all").
	C(c string) BandrejectBuilder
	// CExpr set channels to filter (default "all").
	CExpr(c expr.Expr) BandrejectBuilder
	// Normalize normalize coefficients (default false).
	Normalize(normalize bool) BandrejectBuilder
	// NormalizeExpr normalize coefficients (default false).
	NormalizeExpr(normalize expr.Expr) BandrejectBuilder
	// N normalize coefficients (default false).
	N(n bool) BandrejectBuilder
	// NExpr normalize coefficients (default false).
	NExpr(n expr.Expr) BandrejectBuilder
	// Transform set transform type (from 0 to 6) (default di).
	Transform(transform int) BandrejectBuilder
	// A set transform type (from 0 to 6) (default di).
	A(a int) BandrejectBuilder
	// Precision set filtering precision (from -1 to 3) (default auto).
	Precision(precision int) BandrejectBuilder
	// R set filtering precision (from -1 to 3) (default auto).
	R(r int) BandrejectBuilder
	// Blocksize set the block size (from 0 to 32768) (default 0).
	Blocksize(blocksize int) BandrejectBuilder
	// B set the block size (from 0 to 32768) (default 0).
	B(b int) BandrejectBuilder
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) BandrejectBuilder
}

// Bandreject creates a new BandrejectBuilder to configure the "bandreject" filter.
func Bandreject(opts ...filter.Option) BandrejectBuilder {
	return &implBandrejectBuilder{
		f: filter.New("bandreject", 1, opts...),
	}
}

type implBandrejectBuilder struct {
	f filter.Filter
}

func (bandrejectBuilder *implBandrejectBuilder) String() string {
	return bandrejectBuilder.f.String()
}

func (bandrejectBuilder *implBandrejectBuilder) Outputs() int {
	return bandrejectBuilder.f.Outputs()
}

func (bandrejectBuilder *implBandrejectBuilder) With(key string, value expr.Expr) filter.Filter {
	return bandrejectBuilder.withOption(key, value)
}

func (bandrejectBuilder *implBandrejectBuilder) withOption(key string, value expr.Expr) BandrejectBuilder {
	bCopy := *bandrejectBuilder
	bCopy.f = bandrejectBuilder.f.With(key, value)
	return &bCopy
}

func (bandrejectBuilder *implBandrejectBuilder) Frequency(frequency float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("frequency", expr.Double(frequency))
}

func (bandrejectBuilder *implBandrejectBuilder) FrequencyExpr(frequency expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("frequency", frequency)
}

func (bandrejectBuilder *implBandrejectBuilder) F(f float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("f", expr.Double(f))
}

func (bandrejectBuilder *implBandrejectBuilder) FExpr(f expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("f", f)
}

func (bandrejectBuilder *implBandrejectBuilder) WidthType(widthType int) BandrejectBuilder {
	return bandrejectBuilder.withOption("width_type", expr.Int(widthType))
}

func (bandrejectBuilder *implBandrejectBuilder) WidthTypeExpr(widthType expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("width_type", widthType)
}

func (bandrejectBuilder *implBandrejectBuilder) T(t int) BandrejectBuilder {
	return bandrejectBuilder.withOption("t", expr.Int(t))
}

func (bandrejectBuilder *implBandrejectBuilder) TExpr(t expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("t", t)
}

func (bandrejectBuilder *implBandrejectBuilder) Width(width float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("width", expr.Double(width))
}

func (bandrejectBuilder *implBandrejectBuilder) WidthExpr(width expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("width", width)
}

func (bandrejectBuilder *implBandrejectBuilder) W(w float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("w", expr.Double(w))
}

func (bandrejectBuilder *implBandrejectBuilder) WExpr(w expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("w", w)
}

func (bandrejectBuilder *implBandrejectBuilder) Mix(mix float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("mix", expr.Double(mix))
}

func (bandrejectBuilder *implBandrejectBuilder) MixExpr(mix expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("mix", mix)
}

func (bandrejectBuilder *implBandrejectBuilder) M(m float64) BandrejectBuilder {
	return bandrejectBuilder.withOption("m", expr.Double(m))
}

func (bandrejectBuilder *implBandrejectBuilder) MExpr(m expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("m", m)
}

func (bandrejectBuilder *implBandrejectBuilder) Channels(channels string) BandrejectBuilder {
	return bandrejectBuilder.withOption("channels", expr.String(channels))
}

func (bandrejectBuilder *implBandrejectBuilder) ChannelsExpr(channels expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("channels", channels)
}

func (bandrejectBuilder *implBandrejectBuilder) C(c string) BandrejectBuilder {
	return bandrejectBuilder.withOption("c", expr.String(c))
}

func (bandrejectBuilder *implBandrejectBuilder) CExpr(c expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("c", c)
}

func (bandrejectBuilder *implBandrejectBuilder) Normalize(normalize bool) BandrejectBuilder {
	return bandrejectBuilder.withOption("normalize", expr.Bool(normalize))
}

func (bandrejectBuilder *implBandrejectBuilder) NormalizeExpr(normalize expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("normalize", normalize)
}

func (bandrejectBuilder *implBandrejectBuilder) N(n bool) BandrejectBuilder {
	return bandrejectBuilder.withOption("n", expr.Bool(n))
}

func (bandrejectBuilder *implBandrejectBuilder) NExpr(n expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("n", n)
}

func (bandrejectBuilder *implBandrejectBuilder) Transform(transform int) BandrejectBuilder {
	return bandrejectBuilder.withOption("transform", expr.Int(transform))
}

func (bandrejectBuilder *implBandrejectBuilder) A(a int) BandrejectBuilder {
	return bandrejectBuilder.withOption("a", expr.Int(a))
}

func (bandrejectBuilder *implBandrejectBuilder) Precision(precision int) BandrejectBuilder {
	return bandrejectBuilder.withOption("precision", expr.Int(precision))
}

func (bandrejectBuilder *implBandrejectBuilder) R(r int) BandrejectBuilder {
	return bandrejectBuilder.withOption("r", expr.Int(r))
}

func (bandrejectBuilder *implBandrejectBuilder) Blocksize(blocksize int) BandrejectBuilder {
	return bandrejectBuilder.withOption("blocksize", expr.Int(blocksize))
}

func (bandrejectBuilder *implBandrejectBuilder) B(b int) BandrejectBuilder {
	return bandrejectBuilder.withOption("b", expr.Int(b))
}

func (bandrejectBuilder *implBandrejectBuilder) Enable(enable expr.Expr) BandrejectBuilder {
	return bandrejectBuilder.withOption("enable", enable)
}
