// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// BandpassBuilder Apply a two-pole Butterworth band-pass filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#bandpass
type BandpassBuilder interface {
	filter.Filter
	// Frequency set central frequency (from 0 to 999999) (default 3000).
	Frequency(frequency float64) BandpassBuilder
	// FrequencyExpr set central frequency (from 0 to 999999) (default 3000).
	FrequencyExpr(frequency expr.Expr) BandpassBuilder
	// F set central frequency (from 0 to 999999) (default 3000).
	F(f float64) BandpassBuilder
	// FExpr set central frequency (from 0 to 999999) (default 3000).
	FExpr(f expr.Expr) BandpassBuilder
	// WidthType set filter-width type (from 1 to 5) (default q).
	WidthType(widthType int) BandpassBuilder
	// WidthTypeExpr set filter-width type (from 1 to 5) (default q).
	WidthTypeExpr(widthType expr.Expr) BandpassBuilder
	// T set filter-width type (from 1 to 5) (default q).
	T(t int) BandpassBuilder
	// TExpr set filter-width type (from 1 to 5) (default q).
	TExpr(t expr.Expr) BandpassBuilder
	// Width set width (from 0 to 99999) (default 0.5).
	Width(width float64) BandpassBuilder
	// WidthExpr set width (from 0 to 99999) (default 0.5).
	WidthExpr(width expr.Expr) BandpassBuilder
	// W set width (from 0 to 99999) (default 0.5).
	W(w float64) BandpassBuilder
	// WExpr set width (from 0 to 99999) (default 0.5).
	WExpr(w expr.Expr) BandpassBuilder
	// Csg use constant skirt gain (default false).
	Csg(csg bool) BandpassBuilder
	// CsgExpr use constant skirt gain (default false).
	CsgExpr(csg expr.Expr) BandpassBuilder
	// Mix set mix (from 0 to 1) (default 1).
	Mix(mix float64) BandpassBuilder
	// MixExpr set mix (from 0 to 1) (default 1).
	MixExpr(mix expr.Expr) BandpassBuilder
	// M set mix (from 0 to 1) (default 1).
	M(m float64) BandpassBuilder
	// MExpr set mix (from 0 to 1) (default 1).
	MExpr(m expr.Expr) BandpassBuilder
	// Channels set channels to filter (default "all").
	Channels(channels string) BandpassBuilder
	// ChannelsExpr set channels to filter (default "all").
	ChannelsExpr(channels expr.Expr) BandpassBuilder
	// C set channels to filter (default "all").
	C(c string) BandpassBuilder
	// CExpr set channels to filter (default "all").
	CExpr(c expr.Expr) BandpassBuilder
	// Normalize normalize coefficients (default false).
	Normalize(normalize bool) BandpassBuilder
	// NormalizeExpr normalize coefficients (default false).
	NormalizeExpr(normalize expr.Expr) BandpassBuilder
	// N normalize coefficients (default false).
	N(n bool) BandpassBuilder
	// NExpr normalize coefficients (default false).
	NExpr(n expr.Expr) BandpassBuilder
	// Transform set transform type (from 0 to 6) (default di).
	Transform(transform int) BandpassBuilder
	// A set transform type (from 0 to 6) (default di).
	A(a int) BandpassBuilder
	// Precision set filtering precision (from -1 to 3) (default auto).
	Precision(precision int) BandpassBuilder
	// R set filtering precision (from -1 to 3) (default auto).
	R(r int) BandpassBuilder
	// Blocksize set the block size (from 0 to 32768) (default 0).
	Blocksize(blocksize int) BandpassBuilder
	// B set the block size (from 0 to 32768) (default 0).
	B(b int) BandpassBuilder
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) BandpassBuilder
}

// Bandpass creates a new BandpassBuilder to configure the "bandpass" filter.
func Bandpass(opts ...filter.Option) BandpassBuilder {
	return &implBandpassBuilder{
		f: filter.New("bandpass", 1, opts...),
	}
}

type implBandpassBuilder struct {
	f filter.Filter
}

func (bandpassBuilder *implBandpassBuilder) String() string {
	return bandpassBuilder.f.String()
}

func (bandpassBuilder *implBandpassBuilder) Outputs() int {
	return bandpassBuilder.f.Outputs()
}

func (bandpassBuilder *implBandpassBuilder) With(key string, value expr.Expr) filter.Filter {
	return bandpassBuilder.withOption(key, value)
}

func (bandpassBuilder *implBandpassBuilder) withOption(key string, value expr.Expr) BandpassBuilder {
	bCopy := *bandpassBuilder
	bCopy.f = bandpassBuilder.f.With(key, value)
	return &bCopy
}

func (bandpassBuilder *implBandpassBuilder) Frequency(frequency float64) BandpassBuilder {
	return bandpassBuilder.withOption("frequency", expr.Double(frequency))
}

func (bandpassBuilder *implBandpassBuilder) FrequencyExpr(frequency expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("frequency", frequency)
}

func (bandpassBuilder *implBandpassBuilder) F(f float64) BandpassBuilder {
	return bandpassBuilder.withOption("f", expr.Double(f))
}

func (bandpassBuilder *implBandpassBuilder) FExpr(f expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("f", f)
}

func (bandpassBuilder *implBandpassBuilder) WidthType(widthType int) BandpassBuilder {
	return bandpassBuilder.withOption("width_type", expr.Int(widthType))
}

func (bandpassBuilder *implBandpassBuilder) WidthTypeExpr(widthType expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("width_type", widthType)
}

func (bandpassBuilder *implBandpassBuilder) T(t int) BandpassBuilder {
	return bandpassBuilder.withOption("t", expr.Int(t))
}

func (bandpassBuilder *implBandpassBuilder) TExpr(t expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("t", t)
}

func (bandpassBuilder *implBandpassBuilder) Width(width float64) BandpassBuilder {
	return bandpassBuilder.withOption("width", expr.Double(width))
}

func (bandpassBuilder *implBandpassBuilder) WidthExpr(width expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("width", width)
}

func (bandpassBuilder *implBandpassBuilder) W(w float64) BandpassBuilder {
	return bandpassBuilder.withOption("w", expr.Double(w))
}

func (bandpassBuilder *implBandpassBuilder) WExpr(w expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("w", w)
}

func (bandpassBuilder *implBandpassBuilder) Csg(csg bool) BandpassBuilder {
	return bandpassBuilder.withOption("csg", expr.Bool(csg))
}

func (bandpassBuilder *implBandpassBuilder) CsgExpr(csg expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("csg", csg)
}

func (bandpassBuilder *implBandpassBuilder) Mix(mix float64) BandpassBuilder {
	return bandpassBuilder.withOption("mix", expr.Double(mix))
}

func (bandpassBuilder *implBandpassBuilder) MixExpr(mix expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("mix", mix)
}

func (bandpassBuilder *implBandpassBuilder) M(m float64) BandpassBuilder {
	return bandpassBuilder.withOption("m", expr.Double(m))
}

func (bandpassBuilder *implBandpassBuilder) MExpr(m expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("m", m)
}

func (bandpassBuilder *implBandpassBuilder) Channels(channels string) BandpassBuilder {
	return bandpassBuilder.withOption("channels", expr.String(channels))
}

func (bandpassBuilder *implBandpassBuilder) ChannelsExpr(channels expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("channels", channels)
}

func (bandpassBuilder *implBandpassBuilder) C(c string) BandpassBuilder {
	return bandpassBuilder.withOption("c", expr.String(c))
}

func (bandpassBuilder *implBandpassBuilder) CExpr(c expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("c", c)
}

func (bandpassBuilder *implBandpassBuilder) Normalize(normalize bool) BandpassBuilder {
	return bandpassBuilder.withOption("normalize", expr.Bool(normalize))
}

func (bandpassBuilder *implBandpassBuilder) NormalizeExpr(normalize expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("normalize", normalize)
}

func (bandpassBuilder *implBandpassBuilder) N(n bool) BandpassBuilder {
	return bandpassBuilder.withOption("n", expr.Bool(n))
}

func (bandpassBuilder *implBandpassBuilder) NExpr(n expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("n", n)
}

func (bandpassBuilder *implBandpassBuilder) Transform(transform int) BandpassBuilder {
	return bandpassBuilder.withOption("transform", expr.Int(transform))
}

func (bandpassBuilder *implBandpassBuilder) A(a int) BandpassBuilder {
	return bandpassBuilder.withOption("a", expr.Int(a))
}

func (bandpassBuilder *implBandpassBuilder) Precision(precision int) BandpassBuilder {
	return bandpassBuilder.withOption("precision", expr.Int(precision))
}

func (bandpassBuilder *implBandpassBuilder) R(r int) BandpassBuilder {
	return bandpassBuilder.withOption("r", expr.Int(r))
}

func (bandpassBuilder *implBandpassBuilder) Blocksize(blocksize int) BandpassBuilder {
	return bandpassBuilder.withOption("blocksize", expr.Int(blocksize))
}

func (bandpassBuilder *implBandpassBuilder) B(b int) BandpassBuilder {
	return bandpassBuilder.withOption("b", expr.Int(b))
}

func (bandpassBuilder *implBandpassBuilder) Enable(enable expr.Expr) BandpassBuilder {
	return bandpassBuilder.withOption("enable", enable)
}
