// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// ColorBuilder corresponds to the "color" FFmpeg filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#color
type ColorBuilder interface {
	filter.Filter
	// Size sets the "s" option on the filter.
	Size(width, height int) ColorBuilder
	// FrameRate sets the "r" option on the filter.
	FrameRate(frameRate expr.Expr) ColorBuilder
	// Duration sets the "d" option on the filter.
	Duration(duration string) ColorBuilder
	// Color sets the "c" option on the filter.
	Color(color string) ColorBuilder
}

// Color creates a new ColorBuilder to configure the "color" filter.
func Color(opts ...filter.Option) ColorBuilder {
	return &implColorBuilder{
		f: filter.New("color", 1, opts...),
	}
}

type implColorBuilder struct {
	f filter.Filter
}

func (b *implColorBuilder) String() string {
	return b.f.String()
}

func (b *implColorBuilder) Outputs() int {
	return b.f.Outputs()
}

func (b *implColorBuilder) With(key string, value expr.Expr) filter.Filter {
	return b.withOption(key, value)
}

func (b *implColorBuilder) withOption(key string, value expr.Expr) ColorBuilder {
	bCopy := *b
	bCopy.f = b.f.With(key, value)
	return &bCopy
}

func (b *implColorBuilder) Size(width, height int) ColorBuilder {
	return b.withOption("s", expr.Size(width, height))
}

func (b *implColorBuilder) FrameRate(frameRate expr.Expr) ColorBuilder {
	return b.withOption("r", frameRate)
}

func (b *implColorBuilder) Duration(duration string) ColorBuilder {
	return b.withOption("d", expr.String(duration))
}

func (b *implColorBuilder) Color(color string) ColorBuilder {
	return b.withOption("c", expr.String(color))
}
