// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// DoubleweaveBuilder Weave input video fields into double number of frames.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#doubleweave
type DoubleweaveBuilder interface {
	filter.Filter
	// FirstField set first field (from 0 to 1) (default top).
	FirstField(firstField int) DoubleweaveBuilder
}

// Doubleweave creates a new DoubleweaveBuilder to configure the "doubleweave" filter.
func Doubleweave(opts ...filter.Option) DoubleweaveBuilder {
	return &implDoubleweaveBuilder{
		f: filter.New("doubleweave", 1, opts...),
	}
}

type implDoubleweaveBuilder struct {
	f filter.Filter
}

func (doubleweaveBuilder *implDoubleweaveBuilder) String() string {
	return doubleweaveBuilder.f.String()
}

func (doubleweaveBuilder *implDoubleweaveBuilder) Outputs() int {
	return doubleweaveBuilder.f.Outputs()
}

func (doubleweaveBuilder *implDoubleweaveBuilder) With(key string, value expr.Expr) filter.Filter {
	return doubleweaveBuilder.withOption(key, value)
}

func (doubleweaveBuilder *implDoubleweaveBuilder) withOption(key string, value expr.Expr) DoubleweaveBuilder {
	bCopy := *doubleweaveBuilder
	bCopy.f = doubleweaveBuilder.f.With(key, value)
	return &bCopy
}

func (doubleweaveBuilder *implDoubleweaveBuilder) FirstField(firstField int) DoubleweaveBuilder {
	return doubleweaveBuilder.withOption("first_field", expr.Int(firstField))
}
