// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// HwdownloadBuilder Download a hardware frame to a normal frame.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#hwdownload
type HwdownloadBuilder interface {
	filter.Filter
}

// Hwdownload creates a new HwdownloadBuilder to configure the "hwdownload" filter.
func Hwdownload(opts ...filter.Option) HwdownloadBuilder {
	return &implHwdownloadBuilder{
		f: filter.New("hwdownload", 1, opts...),
	}
}

type implHwdownloadBuilder struct {
	f filter.Filter
}

func (hwdownloadBuilder *implHwdownloadBuilder) String() string {
	return hwdownloadBuilder.f.String()
}

func (hwdownloadBuilder *implHwdownloadBuilder) Outputs() int {
	return hwdownloadBuilder.f.Outputs()
}

func (hwdownloadBuilder *implHwdownloadBuilder) With(key string, value expr.Expr) filter.Filter {
	return hwdownloadBuilder.withOption(key, value)
}

func (hwdownloadBuilder *implHwdownloadBuilder) withOption(key string, value expr.Expr) HwdownloadBuilder {
	bCopy := *hwdownloadBuilder
	bCopy.f = hwdownloadBuilder.f.With(key, value)
	return &bCopy
}
