// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// InflateBuilder Apply inflate effect.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#inflate
type InflateBuilder interface {
	filter.Filter
	// Threshold0 set threshold for 1st plane (from 0 to 65535) (default 65535).
	Threshold0(threshold0 int) InflateBuilder
	// Threshold0Expr set threshold for 1st plane (from 0 to 65535) (default 65535).
	Threshold0Expr(threshold0 expr.Expr) InflateBuilder
	// Threshold1 set threshold for 2nd plane (from 0 to 65535) (default 65535).
	Threshold1(threshold1 int) InflateBuilder
	// Threshold1Expr set threshold for 2nd plane (from 0 to 65535) (default 65535).
	Threshold1Expr(threshold1 expr.Expr) InflateBuilder
	// Threshold2 set threshold for 3rd plane (from 0 to 65535) (default 65535).
	Threshold2(threshold2 int) InflateBuilder
	// Threshold2Expr set threshold for 3rd plane (from 0 to 65535) (default 65535).
	Threshold2Expr(threshold2 expr.Expr) InflateBuilder
	// Threshold3 set threshold for 4th plane (from 0 to 65535) (default 65535).
	Threshold3(threshold3 int) InflateBuilder
	// Threshold3Expr set threshold for 4th plane (from 0 to 65535) (default 65535).
	Threshold3Expr(threshold3 expr.Expr) InflateBuilder
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) InflateBuilder
}

// Inflate creates a new InflateBuilder to configure the "inflate" filter.
func Inflate(opts ...filter.Option) InflateBuilder {
	return &implInflateBuilder{
		f: filter.New("inflate", 1, opts...),
	}
}

type implInflateBuilder struct {
	f filter.Filter
}

func (inflateBuilder *implInflateBuilder) String() string {
	return inflateBuilder.f.String()
}

func (inflateBuilder *implInflateBuilder) Outputs() int {
	return inflateBuilder.f.Outputs()
}

func (inflateBuilder *implInflateBuilder) With(key string, value expr.Expr) filter.Filter {
	return inflateBuilder.withOption(key, value)
}

func (inflateBuilder *implInflateBuilder) withOption(key string, value expr.Expr) InflateBuilder {
	bCopy := *inflateBuilder
	bCopy.f = inflateBuilder.f.With(key, value)
	return &bCopy
}

func (inflateBuilder *implInflateBuilder) Threshold0(threshold0 int) InflateBuilder {
	return inflateBuilder.withOption("threshold0", expr.Int(threshold0))
}

func (inflateBuilder *implInflateBuilder) Threshold0Expr(threshold0 expr.Expr) InflateBuilder {
	return inflateBuilder.withOption("threshold0", threshold0)
}

func (inflateBuilder *implInflateBuilder) Threshold1(threshold1 int) InflateBuilder {
	return inflateBuilder.withOption("threshold1", expr.Int(threshold1))
}

func (inflateBuilder *implInflateBuilder) Threshold1Expr(threshold1 expr.Expr) InflateBuilder {
	return inflateBuilder.withOption("threshold1", threshold1)
}

func (inflateBuilder *implInflateBuilder) Threshold2(threshold2 int) InflateBuilder {
	return inflateBuilder.withOption("threshold2", expr.Int(threshold2))
}

func (inflateBuilder *implInflateBuilder) Threshold2Expr(threshold2 expr.Expr) InflateBuilder {
	return inflateBuilder.withOption("threshold2", threshold2)
}

func (inflateBuilder *implInflateBuilder) Threshold3(threshold3 int) InflateBuilder {
	return inflateBuilder.withOption("threshold3", expr.Int(threshold3))
}

func (inflateBuilder *implInflateBuilder) Threshold3Expr(threshold3 expr.Expr) InflateBuilder {
	return inflateBuilder.withOption("threshold3", threshold3)
}

func (inflateBuilder *implInflateBuilder) Enable(enable expr.Expr) InflateBuilder {
	return inflateBuilder.withOption("enable", enable)
}
