// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// LowpassBuilder Apply a low-pass filter with 3dB point frequency.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#lowpass
type LowpassBuilder interface {
	filter.Filter
	// Frequency set frequency (from 0 to 999999) (default 500).
	Frequency(frequency float64) LowpassBuilder
	// FrequencyExpr set frequency (from 0 to 999999) (default 500).
	FrequencyExpr(frequency expr.Expr) LowpassBuilder
	// F set frequency (from 0 to 999999) (default 500).
	F(f float64) LowpassBuilder
	// FExpr set frequency (from 0 to 999999) (default 500).
	FExpr(f expr.Expr) LowpassBuilder
	// WidthType set filter-width type (from 1 to 5) (default q).
	WidthType(widthType int) LowpassBuilder
	// WidthTypeExpr set filter-width type (from 1 to 5) (default q).
	WidthTypeExpr(widthType expr.Expr) LowpassBuilder
	// T set filter-width type (from 1 to 5) (default q).
	T(t int) LowpassBuilder
	// TExpr set filter-width type (from 1 to 5) (default q).
	TExpr(t expr.Expr) LowpassBuilder
	// Width set width (from 0 to 99999) (default 0.707).
	Width(width float64) LowpassBuilder
	// WidthExpr set width (from 0 to 99999) (default 0.707).
	WidthExpr(width expr.Expr) LowpassBuilder
	// W set width (from 0 to 99999) (default 0.707).
	W(w float64) LowpassBuilder
	// WExpr set width (from 0 to 99999) (default 0.707).
	WExpr(w expr.Expr) LowpassBuilder
	// Poles set number of poles (from 1 to 2) (default 2).
	Poles(poles int) LowpassBuilder
	// P set number of poles (from 1 to 2) (default 2).
	P(p int) LowpassBuilder
	// Mix set mix (from 0 to 1) (default 1).
	Mix(mix float64) LowpassBuilder
	// MixExpr set mix (from 0 to 1) (default 1).
	MixExpr(mix expr.Expr) LowpassBuilder
	// M set mix (from 0 to 1) (default 1).
	M(m float64) LowpassBuilder
	// MExpr set mix (from 0 to 1) (default 1).
	MExpr(m expr.Expr) LowpassBuilder
	// Channels set channels to filter (default "all").
	Channels(channels string) LowpassBuilder
	// ChannelsExpr set channels to filter (default "all").
	ChannelsExpr(channels expr.Expr) LowpassBuilder
	// C set channels to filter (default "all").
	C(c string) LowpassBuilder
	// CExpr set channels to filter (default "all").
	CExpr(c expr.Expr) LowpassBuilder
	// Normalize normalize coefficients (default false).
	Normalize(normalize bool) LowpassBuilder
	// NormalizeExpr normalize coefficients (default false).
	NormalizeExpr(normalize expr.Expr) LowpassBuilder
	// N normalize coefficients (default false).
	N(n bool) LowpassBuilder
	// NExpr normalize coefficients (default false).
	NExpr(n expr.Expr) LowpassBuilder
	// Transform set transform type (from 0 to 6) (default di).
	Transform(transform int) LowpassBuilder
	// A set transform type (from 0 to 6) (default di).
	A(a int) LowpassBuilder
	// Precision set filtering precision (from -1 to 3) (default auto).
	Precision(precision int) LowpassBuilder
	// R set filtering precision (from -1 to 3) (default auto).
	R(r int) LowpassBuilder
	// Blocksize set the block size (from 0 to 32768) (default 0).
	Blocksize(blocksize int) LowpassBuilder
	// B set the block size (from 0 to 32768) (default 0).
	B(b int) LowpassBuilder
}

// Lowpass creates a new LowpassBuilder to configure the "lowpass" filter.
func Lowpass(opts ...filter.Option) LowpassBuilder {
	return &implLowpassBuilder{
		f: filter.New("lowpass", 1, opts...),
	}
}

type implLowpassBuilder struct {
	f filter.Filter
}

func (lowpassBuilder *implLowpassBuilder) String() string {
	return lowpassBuilder.f.String()
}

func (lowpassBuilder *implLowpassBuilder) Outputs() int {
	return lowpassBuilder.f.Outputs()
}

func (lowpassBuilder *implLowpassBuilder) With(key string, value expr.Expr) filter.Filter {
	return lowpassBuilder.withOption(key, value)
}

func (lowpassBuilder *implLowpassBuilder) withOption(key string, value expr.Expr) LowpassBuilder {
	bCopy := *lowpassBuilder
	bCopy.f = lowpassBuilder.f.With(key, value)
	return &bCopy
}

func (lowpassBuilder *implLowpassBuilder) Frequency(frequency float64) LowpassBuilder {
	return lowpassBuilder.withOption("frequency", expr.Double(frequency))
}

func (lowpassBuilder *implLowpassBuilder) FrequencyExpr(frequency expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("frequency", frequency)
}

func (lowpassBuilder *implLowpassBuilder) F(f float64) LowpassBuilder {
	return lowpassBuilder.withOption("f", expr.Double(f))
}

func (lowpassBuilder *implLowpassBuilder) FExpr(f expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("f", f)
}

func (lowpassBuilder *implLowpassBuilder) WidthType(widthType int) LowpassBuilder {
	return lowpassBuilder.withOption("width_type", expr.Int(widthType))
}

func (lowpassBuilder *implLowpassBuilder) WidthTypeExpr(widthType expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("width_type", widthType)
}

func (lowpassBuilder *implLowpassBuilder) T(t int) LowpassBuilder {
	return lowpassBuilder.withOption("t", expr.Int(t))
}

func (lowpassBuilder *implLowpassBuilder) TExpr(t expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("t", t)
}

func (lowpassBuilder *implLowpassBuilder) Width(width float64) LowpassBuilder {
	return lowpassBuilder.withOption("width", expr.Double(width))
}

func (lowpassBuilder *implLowpassBuilder) WidthExpr(width expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("width", width)
}

func (lowpassBuilder *implLowpassBuilder) W(w float64) LowpassBuilder {
	return lowpassBuilder.withOption("w", expr.Double(w))
}

func (lowpassBuilder *implLowpassBuilder) WExpr(w expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("w", w)
}

func (lowpassBuilder *implLowpassBuilder) Poles(poles int) LowpassBuilder {
	return lowpassBuilder.withOption("poles", expr.Int(poles))
}

func (lowpassBuilder *implLowpassBuilder) P(p int) LowpassBuilder {
	return lowpassBuilder.withOption("p", expr.Int(p))
}

func (lowpassBuilder *implLowpassBuilder) Mix(mix float64) LowpassBuilder {
	return lowpassBuilder.withOption("mix", expr.Double(mix))
}

func (lowpassBuilder *implLowpassBuilder) MixExpr(mix expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("mix", mix)
}

func (lowpassBuilder *implLowpassBuilder) M(m float64) LowpassBuilder {
	return lowpassBuilder.withOption("m", expr.Double(m))
}

func (lowpassBuilder *implLowpassBuilder) MExpr(m expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("m", m)
}

func (lowpassBuilder *implLowpassBuilder) Channels(channels string) LowpassBuilder {
	return lowpassBuilder.withOption("channels", expr.String(channels))
}

func (lowpassBuilder *implLowpassBuilder) ChannelsExpr(channels expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("channels", channels)
}

func (lowpassBuilder *implLowpassBuilder) C(c string) LowpassBuilder {
	return lowpassBuilder.withOption("c", expr.String(c))
}

func (lowpassBuilder *implLowpassBuilder) CExpr(c expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("c", c)
}

func (lowpassBuilder *implLowpassBuilder) Normalize(normalize bool) LowpassBuilder {
	return lowpassBuilder.withOption("normalize", expr.Bool(normalize))
}

func (lowpassBuilder *implLowpassBuilder) NormalizeExpr(normalize expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("normalize", normalize)
}

func (lowpassBuilder *implLowpassBuilder) N(n bool) LowpassBuilder {
	return lowpassBuilder.withOption("n", expr.Bool(n))
}

func (lowpassBuilder *implLowpassBuilder) NExpr(n expr.Expr) LowpassBuilder {
	return lowpassBuilder.withOption("n", n)
}

func (lowpassBuilder *implLowpassBuilder) Transform(transform int) LowpassBuilder {
	return lowpassBuilder.withOption("transform", expr.Int(transform))
}

func (lowpassBuilder *implLowpassBuilder) A(a int) LowpassBuilder {
	return lowpassBuilder.withOption("a", expr.Int(a))
}

func (lowpassBuilder *implLowpassBuilder) Precision(precision int) LowpassBuilder {
	return lowpassBuilder.withOption("precision", expr.Int(precision))
}

func (lowpassBuilder *implLowpassBuilder) R(r int) LowpassBuilder {
	return lowpassBuilder.withOption("r", expr.Int(r))
}

func (lowpassBuilder *implLowpassBuilder) Blocksize(blocksize int) LowpassBuilder {
	return lowpassBuilder.withOption("blocksize", expr.Int(blocksize))
}

func (lowpassBuilder *implLowpassBuilder) B(b int) LowpassBuilder {
	return lowpassBuilder.withOption("b", expr.Int(b))
}
