// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// MidequalizerBuilder Apply Midway Equalization.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#midequalizer
type MidequalizerBuilder interface {
	filter.Filter
	// Planes set planes (from 0 to 15) (default 15).
	Planes(planes int) MidequalizerBuilder
}

// Midequalizer creates a new MidequalizerBuilder to configure the "midequalizer" filter.
func Midequalizer(opts ...filter.Option) MidequalizerBuilder {
	return &implMidequalizerBuilder{
		f: filter.New("midequalizer", 1, opts...),
	}
}

type implMidequalizerBuilder struct {
	f filter.Filter
}

func (midequalizerBuilder *implMidequalizerBuilder) String() string {
	return midequalizerBuilder.f.String()
}

func (midequalizerBuilder *implMidequalizerBuilder) Outputs() int {
	return midequalizerBuilder.f.Outputs()
}

func (midequalizerBuilder *implMidequalizerBuilder) With(key string, value expr.Expr) filter.Filter {
	return midequalizerBuilder.withOption(key, value)
}

func (midequalizerBuilder *implMidequalizerBuilder) withOption(key string, value expr.Expr) MidequalizerBuilder {
	bCopy := *midequalizerBuilder
	bCopy.f = midequalizerBuilder.f.With(key, value)
	return &bCopy
}

func (midequalizerBuilder *implMidequalizerBuilder) Planes(planes int) MidequalizerBuilder {
	return midequalizerBuilder.withOption("planes", expr.Int(planes))
}
