// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// NullsinkBuilder Do absolutely nothing with the input video.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#nullsink
type NullsinkBuilder interface {
	filter.Filter
}

// Nullsink creates a new NullsinkBuilder to configure the "nullsink" filter.
func Nullsink(opts ...filter.Option) NullsinkBuilder {
	return &implNullsinkBuilder{
		f: filter.New("nullsink", 1, opts...),
	}
}

type implNullsinkBuilder struct {
	f filter.Filter
}

func (nullsinkBuilder *implNullsinkBuilder) String() string {
	return nullsinkBuilder.f.String()
}

func (nullsinkBuilder *implNullsinkBuilder) Outputs() int {
	return nullsinkBuilder.f.Outputs()
}

func (nullsinkBuilder *implNullsinkBuilder) With(key string, value expr.Expr) filter.Filter {
	return nullsinkBuilder.withOption(key, value)
}

func (nullsinkBuilder *implNullsinkBuilder) withOption(key string, value expr.Expr) NullsinkBuilder {
	bCopy := *nullsinkBuilder
	bCopy.f = nullsinkBuilder.f.With(key, value)
	return &bCopy
}
