// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// ScaleVtBuilder Scale Videotoolbox frames.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#scale_vt
type ScaleVtBuilder interface {
	filter.Filter
	// W Output video width (default "iw").
	W(w string) ScaleVtBuilder
	// H Output video height (default "ih").
	H(h string) ScaleVtBuilder
	// ColorMatrix Output colour matrix coefficient set.
	ColorMatrix(colorMatrix string) ScaleVtBuilder
	// ColorPrimaries Output colour primaries.
	ColorPrimaries(colorPrimaries string) ScaleVtBuilder
	// ColorTransfer Output colour transfer characteristics.
	ColorTransfer(colorTransfer string) ScaleVtBuilder
}

// ScaleVt creates a new ScaleVtBuilder to configure the "scale_vt" filter.
func ScaleVt(opts ...filter.Option) ScaleVtBuilder {
	return &implScaleVtBuilder{
		f: filter.New("scale_vt", 1, opts...),
	}
}

type implScaleVtBuilder struct {
	f filter.Filter
}

func (scale_vtBuilder *implScaleVtBuilder) String() string {
	return scale_vtBuilder.f.String()
}

func (scale_vtBuilder *implScaleVtBuilder) Outputs() int {
	return scale_vtBuilder.f.Outputs()
}

func (scale_vtBuilder *implScaleVtBuilder) With(key string, value expr.Expr) filter.Filter {
	return scale_vtBuilder.withOption(key, value)
}

func (scale_vtBuilder *implScaleVtBuilder) withOption(key string, value expr.Expr) ScaleVtBuilder {
	bCopy := *scale_vtBuilder
	bCopy.f = scale_vtBuilder.f.With(key, value)
	return &bCopy
}

func (scale_vtBuilder *implScaleVtBuilder) W(w string) ScaleVtBuilder {
	return scale_vtBuilder.withOption("w", expr.String(w))
}

func (scale_vtBuilder *implScaleVtBuilder) H(h string) ScaleVtBuilder {
	return scale_vtBuilder.withOption("h", expr.String(h))
}

func (scale_vtBuilder *implScaleVtBuilder) ColorMatrix(colorMatrix string) ScaleVtBuilder {
	return scale_vtBuilder.withOption("color_matrix", expr.String(colorMatrix))
}

func (scale_vtBuilder *implScaleVtBuilder) ColorPrimaries(colorPrimaries string) ScaleVtBuilder {
	return scale_vtBuilder.withOption("color_primaries", expr.String(colorPrimaries))
}

func (scale_vtBuilder *implScaleVtBuilder) ColorTransfer(colorTransfer string) ScaleVtBuilder {
	return scale_vtBuilder.withOption("color_transfer", expr.String(colorTransfer))
}
