// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// SetparamsBuilder Force field, or color property for the output video frame.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#setparams
type SetparamsBuilder interface {
	filter.Filter
	// FieldMode select interlace mode (from -1 to 2) (default auto).
	FieldMode(fieldMode int) SetparamsBuilder
	// Range select color range (from -1 to 2) (default auto).
	Range(rng int) SetparamsBuilder
	// ColorPrimaries select color primaries (from -1 to 22) (default auto).
	ColorPrimaries(colorPrimaries int) SetparamsBuilder
	// ColorTrc select color transfer (from -1 to 18) (default auto).
	ColorTrc(colorTrc int) SetparamsBuilder
	// Colorspace select colorspace (from -1 to 14) (default auto).
	Colorspace(colorspace int) SetparamsBuilder
}

// Setparams creates a new SetparamsBuilder to configure the "setparams" filter.
func Setparams(opts ...filter.Option) SetparamsBuilder {
	return &implSetparamsBuilder{
		f: filter.New("setparams", 1, opts...),
	}
}

type implSetparamsBuilder struct {
	f filter.Filter
}

func (setparamsBuilder *implSetparamsBuilder) String() string {
	return setparamsBuilder.f.String()
}

func (setparamsBuilder *implSetparamsBuilder) Outputs() int {
	return setparamsBuilder.f.Outputs()
}

func (setparamsBuilder *implSetparamsBuilder) With(key string, value expr.Expr) filter.Filter {
	return setparamsBuilder.withOption(key, value)
}

func (setparamsBuilder *implSetparamsBuilder) withOption(key string, value expr.Expr) SetparamsBuilder {
	bCopy := *setparamsBuilder
	bCopy.f = setparamsBuilder.f.With(key, value)
	return &bCopy
}

func (setparamsBuilder *implSetparamsBuilder) FieldMode(fieldMode int) SetparamsBuilder {
	return setparamsBuilder.withOption("field_mode", expr.Int(fieldMode))
}

func (setparamsBuilder *implSetparamsBuilder) Range(rng int) SetparamsBuilder {
	return setparamsBuilder.withOption("range", expr.Int(rng))
}

func (setparamsBuilder *implSetparamsBuilder) ColorPrimaries(colorPrimaries int) SetparamsBuilder {
	return setparamsBuilder.withOption("color_primaries", expr.Int(colorPrimaries))
}

func (setparamsBuilder *implSetparamsBuilder) ColorTrc(colorTrc int) SetparamsBuilder {
	return setparamsBuilder.withOption("color_trc", expr.Int(colorTrc))
}

func (setparamsBuilder *implSetparamsBuilder) Colorspace(colorspace int) SetparamsBuilder {
	return setparamsBuilder.withOption("colorspace", expr.Int(colorspace))
}
