// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// ShowfreqsBuilder Convert input audio to a frequencies video output.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#showfreqs
type ShowfreqsBuilder interface {
	filter.Filter
	// Size set video size (default "1024x512").
	Size(size expr.Size) ShowfreqsBuilder
	// S set video size (default "1024x512").
	S(s expr.Size) ShowfreqsBuilder
	// Rate set video rate (default "25").
	Rate(rate expr.Rational) ShowfreqsBuilder
	// R set video rate (default "25").
	R(r expr.Rational) ShowfreqsBuilder
	// Mode set display mode (from 0 to 2) (default bar).
	Mode(mode int) ShowfreqsBuilder
	// Ascale set amplitude scale (from 0 to 3) (default log).
	Ascale(ascale int) ShowfreqsBuilder
	// Fscale set frequency scale (from 0 to 2) (default lin).
	Fscale(fscale int) ShowfreqsBuilder
	// WinSize set window size (from 16 to 65536) (default 2048).
	WinSize(winSize int) ShowfreqsBuilder
	// WinFunc set window function (from 0 to 20) (default hann).
	WinFunc(winFunc int) ShowfreqsBuilder
	// Overlap set window overlap (from 0 to 1) (default 1).
	Overlap(overlap float32) ShowfreqsBuilder
	// Averaging set time averaging (from 0 to INT_MAX) (default 1).
	Averaging(averaging int) ShowfreqsBuilder
	// Colors set channels colors (default "red|green|blue|yellow|orange|lime|pink|magenta|brown").
	Colors(colors string) ShowfreqsBuilder
	// Cmode set channel mode (from 0 to 1) (default combined).
	Cmode(cmode int) ShowfreqsBuilder
	// Minamp set minimum amplitude (from FLT_MIN to 1e-06) (default 1e-06).
	Minamp(minamp float32) ShowfreqsBuilder
	// Data set data mode (from 0 to 2) (default magnitude).
	Data(data int) ShowfreqsBuilder
	// Channels set channels to draw (default "all").
	Channels(channels string) ShowfreqsBuilder
}

// Showfreqs creates a new ShowfreqsBuilder to configure the "showfreqs" filter.
func Showfreqs(opts ...filter.Option) ShowfreqsBuilder {
	return &implShowfreqsBuilder{
		f: filter.New("showfreqs", 1, opts...),
	}
}

type implShowfreqsBuilder struct {
	f filter.Filter
}

func (showfreqsBuilder *implShowfreqsBuilder) String() string {
	return showfreqsBuilder.f.String()
}

func (showfreqsBuilder *implShowfreqsBuilder) Outputs() int {
	return showfreqsBuilder.f.Outputs()
}

func (showfreqsBuilder *implShowfreqsBuilder) With(key string, value expr.Expr) filter.Filter {
	return showfreqsBuilder.withOption(key, value)
}

func (showfreqsBuilder *implShowfreqsBuilder) withOption(key string, value expr.Expr) ShowfreqsBuilder {
	bCopy := *showfreqsBuilder
	bCopy.f = showfreqsBuilder.f.With(key, value)
	return &bCopy
}

func (showfreqsBuilder *implShowfreqsBuilder) Size(size expr.Size) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("size", size)
}

func (showfreqsBuilder *implShowfreqsBuilder) S(s expr.Size) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("s", s)
}

func (showfreqsBuilder *implShowfreqsBuilder) Rate(rate expr.Rational) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("rate", rate)
}

func (showfreqsBuilder *implShowfreqsBuilder) R(r expr.Rational) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("r", r)
}

func (showfreqsBuilder *implShowfreqsBuilder) Mode(mode int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("mode", expr.Int(mode))
}

func (showfreqsBuilder *implShowfreqsBuilder) Ascale(ascale int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("ascale", expr.Int(ascale))
}

func (showfreqsBuilder *implShowfreqsBuilder) Fscale(fscale int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("fscale", expr.Int(fscale))
}

func (showfreqsBuilder *implShowfreqsBuilder) WinSize(winSize int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("win_size", expr.Int(winSize))
}

func (showfreqsBuilder *implShowfreqsBuilder) WinFunc(winFunc int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("win_func", expr.Int(winFunc))
}

func (showfreqsBuilder *implShowfreqsBuilder) Overlap(overlap float32) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("overlap", expr.Float(overlap))
}

func (showfreqsBuilder *implShowfreqsBuilder) Averaging(averaging int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("averaging", expr.Int(averaging))
}

func (showfreqsBuilder *implShowfreqsBuilder) Colors(colors string) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("colors", expr.String(colors))
}

func (showfreqsBuilder *implShowfreqsBuilder) Cmode(cmode int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("cmode", expr.Int(cmode))
}

func (showfreqsBuilder *implShowfreqsBuilder) Minamp(minamp float32) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("minamp", expr.Float(minamp))
}

func (showfreqsBuilder *implShowfreqsBuilder) Data(data int) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("data", expr.Int(data))
}

func (showfreqsBuilder *implShowfreqsBuilder) Channels(channels string) ShowfreqsBuilder {
	return showfreqsBuilder.withOption("channels", expr.String(channels))
}
