// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// SmartblurBuilder Blur the input video without impacting the outlines.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#smartblur
type SmartblurBuilder interface {
	filter.Filter
	// LumaRadius set luma radius (from 0.1 to 5) (default 1).
	LumaRadius(lumaRadius float32) SmartblurBuilder
	// Lr set luma radius (from 0.1 to 5) (default 1).
	Lr(lr float32) SmartblurBuilder
	// LumaStrength set luma strength (from -1 to 1) (default 1).
	LumaStrength(lumaStrength float32) SmartblurBuilder
	// Ls set luma strength (from -1 to 1) (default 1).
	Ls(ls float32) SmartblurBuilder
	// LumaThreshold set luma threshold (from -30 to 30) (default 0).
	LumaThreshold(lumaThreshold int) SmartblurBuilder
	// Lt set luma threshold (from -30 to 30) (default 0).
	Lt(lt int) SmartblurBuilder
	// ChromaRadius set chroma radius (from -0.9 to 5) (default -0.9).
	ChromaRadius(chromaRadius float32) SmartblurBuilder
	// Cr set chroma radius (from -0.9 to 5) (default -0.9).
	Cr(cr float32) SmartblurBuilder
	// ChromaStrength set chroma strength (from -2 to 1) (default -2).
	ChromaStrength(chromaStrength float32) SmartblurBuilder
	// Cs set chroma strength (from -2 to 1) (default -2).
	Cs(cs float32) SmartblurBuilder
	// ChromaThreshold set chroma threshold (from -31 to 30) (default -31).
	ChromaThreshold(chromaThreshold int) SmartblurBuilder
	// Ct set chroma threshold (from -31 to 30) (default -31).
	Ct(ct int) SmartblurBuilder
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) SmartblurBuilder
}

// Smartblur creates a new SmartblurBuilder to configure the "smartblur" filter.
func Smartblur(opts ...filter.Option) SmartblurBuilder {
	return &implSmartblurBuilder{
		f: filter.New("smartblur", 1, opts...),
	}
}

type implSmartblurBuilder struct {
	f filter.Filter
}

func (smartblurBuilder *implSmartblurBuilder) String() string {
	return smartblurBuilder.f.String()
}

func (smartblurBuilder *implSmartblurBuilder) Outputs() int {
	return smartblurBuilder.f.Outputs()
}

func (smartblurBuilder *implSmartblurBuilder) With(key string, value expr.Expr) filter.Filter {
	return smartblurBuilder.withOption(key, value)
}

func (smartblurBuilder *implSmartblurBuilder) withOption(key string, value expr.Expr) SmartblurBuilder {
	bCopy := *smartblurBuilder
	bCopy.f = smartblurBuilder.f.With(key, value)
	return &bCopy
}

func (smartblurBuilder *implSmartblurBuilder) LumaRadius(lumaRadius float32) SmartblurBuilder {
	return smartblurBuilder.withOption("luma_radius", expr.Float(lumaRadius))
}

func (smartblurBuilder *implSmartblurBuilder) Lr(lr float32) SmartblurBuilder {
	return smartblurBuilder.withOption("lr", expr.Float(lr))
}

func (smartblurBuilder *implSmartblurBuilder) LumaStrength(lumaStrength float32) SmartblurBuilder {
	return smartblurBuilder.withOption("luma_strength", expr.Float(lumaStrength))
}

func (smartblurBuilder *implSmartblurBuilder) Ls(ls float32) SmartblurBuilder {
	return smartblurBuilder.withOption("ls", expr.Float(ls))
}

func (smartblurBuilder *implSmartblurBuilder) LumaThreshold(lumaThreshold int) SmartblurBuilder {
	return smartblurBuilder.withOption("luma_threshold", expr.Int(lumaThreshold))
}

func (smartblurBuilder *implSmartblurBuilder) Lt(lt int) SmartblurBuilder {
	return smartblurBuilder.withOption("lt", expr.Int(lt))
}

func (smartblurBuilder *implSmartblurBuilder) ChromaRadius(chromaRadius float32) SmartblurBuilder {
	return smartblurBuilder.withOption("chroma_radius", expr.Float(chromaRadius))
}

func (smartblurBuilder *implSmartblurBuilder) Cr(cr float32) SmartblurBuilder {
	return smartblurBuilder.withOption("cr", expr.Float(cr))
}

func (smartblurBuilder *implSmartblurBuilder) ChromaStrength(chromaStrength float32) SmartblurBuilder {
	return smartblurBuilder.withOption("chroma_strength", expr.Float(chromaStrength))
}

func (smartblurBuilder *implSmartblurBuilder) Cs(cs float32) SmartblurBuilder {
	return smartblurBuilder.withOption("cs", expr.Float(cs))
}

func (smartblurBuilder *implSmartblurBuilder) ChromaThreshold(chromaThreshold int) SmartblurBuilder {
	return smartblurBuilder.withOption("chroma_threshold", expr.Int(chromaThreshold))
}

func (smartblurBuilder *implSmartblurBuilder) Ct(ct int) SmartblurBuilder {
	return smartblurBuilder.withOption("ct", expr.Int(ct))
}

func (smartblurBuilder *implSmartblurBuilder) Enable(enable expr.Expr) SmartblurBuilder {
	return smartblurBuilder.withOption("enable", enable)
}
