// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// SMPTEBarsBuilder corresponds to the "smptebars" FFmpeg filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#smptebars
type SMPTEBarsBuilder interface {
	filter.Filter
	// Size sets the "s" option on the filter.
	Size(width, height int) SMPTEBarsBuilder
	// FrameRate sets the "r" option on the filter.
	FrameRate(frameRate expr.Expr) SMPTEBarsBuilder
	// Duration sets the "d" option on the filter.
	Duration(duration string) SMPTEBarsBuilder
}

// SMPTEBars creates a new SMPTEBarsBuilder to configure the "smptebars" filter.
func SMPTEBars(opts ...filter.Option) SMPTEBarsBuilder {
	return &implSMPTEBarsBuilder{
		f: filter.New("smptebars", 1, opts...),
	}
}

type implSMPTEBarsBuilder struct {
	f filter.Filter
}

func (b *implSMPTEBarsBuilder) String() string {
	return b.f.String()
}

func (b *implSMPTEBarsBuilder) Outputs() int {
	return b.f.Outputs()
}

func (b *implSMPTEBarsBuilder) With(key string, value expr.Expr) filter.Filter {
	return b.withOption(key, value)
}

func (b *implSMPTEBarsBuilder) withOption(key string, value expr.Expr) SMPTEBarsBuilder {
	bCopy := *b
	bCopy.f = b.f.With(key, value)
	return &bCopy
}

func (b *implSMPTEBarsBuilder) Size(width, height int) SMPTEBarsBuilder {
	return b.withOption("s", expr.Size(width, height))
}

func (b *implSMPTEBarsBuilder) FrameRate(frameRate expr.Expr) SMPTEBarsBuilder {
	return b.withOption("r", frameRate)
}

func (b *implSMPTEBarsBuilder) Duration(duration string) SMPTEBarsBuilder {
	return b.withOption("d", expr.String(duration))
}
