// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// SwapuvBuilder Swap U and V components.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#swapuv
type SwapuvBuilder interface {
	filter.Filter
}

// Swapuv creates a new SwapuvBuilder to configure the "swapuv" filter.
func Swapuv(opts ...filter.Option) SwapuvBuilder {
	return &implSwapuvBuilder{
		f: filter.New("swapuv", 1, opts...),
	}
}

type implSwapuvBuilder struct {
	f filter.Filter
}

func (swapuvBuilder *implSwapuvBuilder) String() string {
	return swapuvBuilder.f.String()
}

func (swapuvBuilder *implSwapuvBuilder) Outputs() int {
	return swapuvBuilder.f.Outputs()
}

func (swapuvBuilder *implSwapuvBuilder) With(key string, value expr.Expr) filter.Filter {
	return swapuvBuilder.withOption(key, value)
}

func (swapuvBuilder *implSwapuvBuilder) withOption(key string, value expr.Expr) SwapuvBuilder {
	bCopy := *swapuvBuilder
	bCopy.f = swapuvBuilder.f.With(key, value)
	return &bCopy
}
