// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// TiltandshiftBuilder Generate a tilt-and-shift'd video.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#tiltandshift
type TiltandshiftBuilder interface {
	filter.Filter
}

// Tiltandshift creates a new TiltandshiftBuilder to configure the "tiltandshift" filter.
func Tiltandshift(opts ...filter.Option) TiltandshiftBuilder {
	return &implTiltandshiftBuilder{
		f: filter.New("tiltandshift", 1, opts...),
	}
}

type implTiltandshiftBuilder struct {
	f filter.Filter
}

func (tiltandshiftBuilder *implTiltandshiftBuilder) String() string {
	return tiltandshiftBuilder.f.String()
}

func (tiltandshiftBuilder *implTiltandshiftBuilder) Outputs() int {
	return tiltandshiftBuilder.f.Outputs()
}

func (tiltandshiftBuilder *implTiltandshiftBuilder) With(key string, value expr.Expr) filter.Filter {
	return tiltandshiftBuilder.withOption(key, value)
}

func (tiltandshiftBuilder *implTiltandshiftBuilder) withOption(key string, value expr.Expr) TiltandshiftBuilder {
	bCopy := *tiltandshiftBuilder
	bCopy.f = tiltandshiftBuilder.f.With(key, value)
	return &bCopy
}
