// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// VfrdetBuilder Variable frame rate detect filter.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#vfrdet
type VfrdetBuilder interface {
	filter.Filter
}

// Vfrdet creates a new VfrdetBuilder to configure the "vfrdet" filter.
func Vfrdet(opts ...filter.Option) VfrdetBuilder {
	return &implVfrdetBuilder{
		f: filter.New("vfrdet", 1, opts...),
	}
}

type implVfrdetBuilder struct {
	f filter.Filter
}

func (vfrdetBuilder *implVfrdetBuilder) String() string {
	return vfrdetBuilder.f.String()
}

func (vfrdetBuilder *implVfrdetBuilder) Outputs() int {
	return vfrdetBuilder.f.Outputs()
}

func (vfrdetBuilder *implVfrdetBuilder) With(key string, value expr.Expr) filter.Filter {
	return vfrdetBuilder.withOption(key, value)
}

func (vfrdetBuilder *implVfrdetBuilder) withOption(key string, value expr.Expr) VfrdetBuilder {
	bCopy := *vfrdetBuilder
	bCopy.f = vfrdetBuilder.f.With(key, value)
	return &bCopy
}
