// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// VirtualbassBuilder Audio Virtual Bass.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#virtualbass
type VirtualbassBuilder interface {
	filter.Filter
	// Cutoff set virtual bass cutoff (from 100 to 500) (default 250).
	Cutoff(cutoff float64) VirtualbassBuilder
	// Strength set virtual bass strength (from 0.5 to 3) (default 3).
	Strength(strength float64) VirtualbassBuilder
	// StrengthExpr set virtual bass strength (from 0.5 to 3) (default 3).
	StrengthExpr(strength expr.Expr) VirtualbassBuilder
	// Enable expression to enable or disable the filter.
	Enable(enable expr.Expr) VirtualbassBuilder
}

// Virtualbass creates a new VirtualbassBuilder to configure the "virtualbass" filter.
func Virtualbass(opts ...filter.Option) VirtualbassBuilder {
	return &implVirtualbassBuilder{
		f: filter.New("virtualbass", 1, opts...),
	}
}

type implVirtualbassBuilder struct {
	f filter.Filter
}

func (virtualbassBuilder *implVirtualbassBuilder) String() string {
	return virtualbassBuilder.f.String()
}

func (virtualbassBuilder *implVirtualbassBuilder) Outputs() int {
	return virtualbassBuilder.f.Outputs()
}

func (virtualbassBuilder *implVirtualbassBuilder) With(key string, value expr.Expr) filter.Filter {
	return virtualbassBuilder.withOption(key, value)
}

func (virtualbassBuilder *implVirtualbassBuilder) withOption(key string, value expr.Expr) VirtualbassBuilder {
	bCopy := *virtualbassBuilder
	bCopy.f = virtualbassBuilder.f.With(key, value)
	return &bCopy
}

func (virtualbassBuilder *implVirtualbassBuilder) Cutoff(cutoff float64) VirtualbassBuilder {
	return virtualbassBuilder.withOption("cutoff", expr.Double(cutoff))
}

func (virtualbassBuilder *implVirtualbassBuilder) Strength(strength float64) VirtualbassBuilder {
	return virtualbassBuilder.withOption("strength", expr.Double(strength))
}

func (virtualbassBuilder *implVirtualbassBuilder) StrengthExpr(strength expr.Expr) VirtualbassBuilder {
	return virtualbassBuilder.withOption("strength", strength)
}

func (virtualbassBuilder *implVirtualbassBuilder) Enable(enable expr.Expr) VirtualbassBuilder {
	return virtualbassBuilder.withOption("enable", enable)
}
