// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// VolumedetectBuilder Detect audio volume.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#volumedetect
type VolumedetectBuilder interface {
	filter.Filter
}

// Volumedetect creates a new VolumedetectBuilder to configure the "volumedetect" filter.
func Volumedetect(opts ...filter.Option) VolumedetectBuilder {
	return &implVolumedetectBuilder{
		f: filter.New("volumedetect", 1, opts...),
	}
}

type implVolumedetectBuilder struct {
	f filter.Filter
}

func (volumedetectBuilder *implVolumedetectBuilder) String() string {
	return volumedetectBuilder.f.String()
}

func (volumedetectBuilder *implVolumedetectBuilder) Outputs() int {
	return volumedetectBuilder.f.Outputs()
}

func (volumedetectBuilder *implVolumedetectBuilder) With(key string, value expr.Expr) filter.Filter {
	return volumedetectBuilder.withOption(key, value)
}

func (volumedetectBuilder *implVolumedetectBuilder) withOption(key string, value expr.Expr) VolumedetectBuilder {
	bCopy := *volumedetectBuilder
	bCopy.f = volumedetectBuilder.f.With(key, value)
	return &bCopy
}
