// Code generated by cmd/filtergen. DO NOT EDIT.

package filters

import (
	"github.com/spiretechnology/spireav/filter"
	"github.com/spiretechnology/spireav/filter/expr"
)

// XcorrelateBuilder Cross-correlate first video stream with second video stream.
// Documentation: https://ffmpeg.org/ffmpeg-filters.html#xcorrelate
type XcorrelateBuilder interface {
	filter.Filter
	// Planes set planes to cross-correlate (from 0 to 15) (default 7).
	Planes(planes int) XcorrelateBuilder
	// Secondary when to process secondary frame (from 0 to 1) (default all).
	Secondary(secondary int) XcorrelateBuilder
	// EofAction Action to take when encountering EOF from secondary input  (from 0 to 2) (default repeat).
	EofAction(eofAction int) XcorrelateBuilder
	// Shortest force termination when the shortest input terminates (default false).
	Shortest(shortest bool) XcorrelateBuilder
	// Repeatlast extend last frame of secondary streams beyond EOF (default true).
	Repeatlast(repeatlast bool) XcorrelateBuilder
	// TsSyncMode How strictly to sync streams based on secondary input timestamps (from 0 to 1) (default default).
	TsSyncMode(tsSyncMode int) XcorrelateBuilder
}

// Xcorrelate creates a new XcorrelateBuilder to configure the "xcorrelate" filter.
func Xcorrelate(opts ...filter.Option) XcorrelateBuilder {
	return &implXcorrelateBuilder{
		f: filter.New("xcorrelate", 1, opts...),
	}
}

type implXcorrelateBuilder struct {
	f filter.Filter
}

func (xcorrelateBuilder *implXcorrelateBuilder) String() string {
	return xcorrelateBuilder.f.String()
}

func (xcorrelateBuilder *implXcorrelateBuilder) Outputs() int {
	return xcorrelateBuilder.f.Outputs()
}

func (xcorrelateBuilder *implXcorrelateBuilder) With(key string, value expr.Expr) filter.Filter {
	return xcorrelateBuilder.withOption(key, value)
}

func (xcorrelateBuilder *implXcorrelateBuilder) withOption(key string, value expr.Expr) XcorrelateBuilder {
	bCopy := *xcorrelateBuilder
	bCopy.f = xcorrelateBuilder.f.With(key, value)
	return &bCopy
}

func (xcorrelateBuilder *implXcorrelateBuilder) Planes(planes int) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("planes", expr.Int(planes))
}

func (xcorrelateBuilder *implXcorrelateBuilder) Secondary(secondary int) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("secondary", expr.Int(secondary))
}

func (xcorrelateBuilder *implXcorrelateBuilder) EofAction(eofAction int) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("eof_action", expr.Int(eofAction))
}

func (xcorrelateBuilder *implXcorrelateBuilder) Shortest(shortest bool) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("shortest", expr.Bool(shortest))
}

func (xcorrelateBuilder *implXcorrelateBuilder) Repeatlast(repeatlast bool) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("repeatlast", expr.Bool(repeatlast))
}

func (xcorrelateBuilder *implXcorrelateBuilder) TsSyncMode(tsSyncMode int) XcorrelateBuilder {
	return xcorrelateBuilder.withOption("ts_sync_mode", expr.Int(tsSyncMode))
}
