name: Pull Request Workflow
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:

    - name: Install FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Test
      run: go test ./...

  test-windows:
    name: Build, Test on Windows
    runs-on: windows-2019
    steps:

    - name: Install FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      env:
        TEMP_DIR: '.'
      run: go test ./...
